### ISSUE TITLE
Dobot does not respond with this library!

### ISSUE THREAD

**Issue by uncommonthinker** [luismesas/pydobot#1]
Hi @lusimesas, i am using Dobot black board, and as much as i would love to use your code to control Dobot, it wouldn't respond. Are there any setup steps i am missing?

I tried with 2.7 with errors, then i tried with 3.5 and there are no errors, the code runs but there is no response from Dobot.

**Comment by floodsung** [comment]
the same problem

**Comment by luismesas** [comment]
Hi,

This has now been solved, command queue needed to be activated in order for the dobot to respond in the latest firmware versions.

**Comment by dparkar** [comment]
Still facing the same issue with v1.0.2

**Comment by uncommonthinker** [comment]
@dparkar Use the updated version of pydobot
