### ISSUE TITLE
How to connect on Windows 10 

### ISSUE THREAD

**Issue by evrenmercan** [luismesas/pydobot#10]
Dear All , 
How to must be mask for Windows 10 ??
 "available_ports = glob('/dev/cu*usb*')"  

Thank you

**Comment by luismesas** [comment]
Hi @evrenmercan  ,

I updated the basic example to use the first available port, please let me know if this helps. I tested it on a Windows 10 and it works now.

PS: I know I'm replying a year late, but I guess I owe you an answer :)
