### ISSUE TITLE
struct.error: unpack_from requires a buffer of at least 4 bytes

### ISSUE THREAD

**Issue by sandipan1** [luismesas/pydobot#11]
while executing dobot.py line 96 in _get_pose 
self.j3 = struct.unpack_from('f', response.params, 24)[0]
getting "struct.error: unpack_from requires a buffer of at least 4 bytes"

**Comment by KujiragiKamura** [comment]
Do you found a solution for this problem?

**Comment by sandipan1** [comment]
Nope. Not using this library anymore

**Comment by XianglongNickTan** [comment]
> Do you found a solution for this problem?

Hi there, I had the same issue but solved it by resetting the robot. Help this will help.
