### ISSUE TITLE
pydobot on win7 jupyter - connection problem.

### ISSUE THREAD

**Issue by ivldmitriy** [luismesas/pydobot#7]
Hi, luismesas!

I work under Win7 OS, in Jupyter notebook.
I have a problem - how should i configure the appropriate port for my Dobot?

Thanx a lot for your work.

**Comment by luismesas** [comment]
Hi @ivldmitriy not sure if a jupyter notebook manages connections, but I updated the basic example using the first available port in the computer, please let me know if that helps.
