### ISSUE TITLE
I need help with gripper codes with python not in dobot studio

### ISSUE THREAD

**Issue by TINLIANG** [luismesas/pydobot#8]
I would appreciate help with how to write the codes to activate the gripper with python out of dobot studio.

**Comment by TINLIANG** [comment]
I also need help with setting home of the dobot. Do I have to add in the library of my pydobot?

**Comment by luismesas** [comment]
I just added gripper compatibility based on the code shared in another issue.

**Comment by luismesas** [comment]
@TINLIANG setting home will require control of ALERTS (to handle of limits) it's something I have pending to add.
