### ISSUE TITLE
No port found for Dobot Magician

### ISSUE THREAD

**Issue by bjeong99** [luismesas/pydobot#9]
Hi, for some reason the port can't be found for the Dobot Magician. I have it connected to COM4 and I checked the connection, but the problem persists. Do you have suggestions? Thanks.

**Comment by luismesas** [comment]
Hi @bjeong99 ,

I updated the basic example to use the first available port, please let me know if this helps

PS: I know I'm replying a year late, but I guess I owe you an answer :)
